# Generated by Django 5.0.6 on 2025-03-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
